FROM node:latest As development
# ARG DATABASE_URL=postgresql://alexgray:testing12345@localhost:5432/tododatabase?schema=public
# ENV DATABASE_URL $DATABASE_URL

# WORKDIR /usr/src/app

# COPY . .

# RUN npm install -g npm@7.6.3
# RUN npm install